export const TODOS_FETCH_IN_PROGRESS = "TODOS_FETCH_IN_PROGRESS"
export const TODOS_FETCH_SUCCESS = "TODOS_FETCH_SUCCESS";
export const TODOS_FETCH_FAILED = "TODOS_FETCH_FAILED";

export const TODOS_FORM_SUCCESS = "TODOS_FORM_SUCCESS";
export const TODOS_FORM_IN_PROGRESS = "TODOS_FORM_IN_PROGRESS"
export const TODOS_FORM_FAILED = "TODOS_FORM_FAILED"
